# Generated by Django 4.1.3 on 2022-12-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_order_tags_product_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_date",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created_date",
            new_name="date_created",
        ),
    ]
