# Generated by Django 4.1.3 on 2022-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_created_date_order_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
